import React,{useEffect,useState} from 'react';
import {summarizeAttendance} from '../shared/attendance';
const cell=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';
function exportRows(name,rows){const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
const date=t=>t?new Date(t).toLocaleString():'Present';
export default function Attendance({load,onClose}){
 const [report,setReport]=useState(null),[error,setError]=useState(''),[filter,setFilter]=useState(''),[search,setSearch]=useState('');
 async function refresh(){try{const r=await load();setReport(r);setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{refresh();const timer=setInterval(refresh,15000);return()=>clearInterval(timer);},[]);
 const visits=(report?.rows||[]).filter(r=>(!filter||r.meetingId===filter)&&r.name.toLowerCase().includes(search.toLowerCase()));
 const rows=summarizeAttendance(visits,report?.now||Date.now());
 return <section className="attendance-screen"><header className="studio-header"><div><strong>Attendance tracker</strong><small>{report?.permanent?'Saved meeting history':'Temporary meeting records'} · Refreshes every 15 seconds</small></div><button onClick={onClose}>Close attendance</button></header>{error&&<p className="error">{error}</p>}<div className="attendance-controls"><label>Session<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All sessions</option>{report?.meetings?.map(m=><option key={m.id} value={m.id}>{date(m.startedAt)} {m.endedAt?'· ended':'· current'}</option>)}</select></label><label>Search participant<input value={search} onChange={e=>setSearch(e.target.value)}/></label><button onClick={refresh}>Refresh</button><button disabled={!report} onClick={()=>exportRows('skymeet-attendance-summary.csv',[['Name','Participant key','Session','First joined','Last left','Minutes','Visits','Status'],...rows.map(r=>[r.name,r.personId,r.meetingId,date(r.joinedAt),r.live?'Present':date(r.leftAt),(r.total/60000).toFixed(2),r.visits,r.live?'Present':'Left'])])}>Summary CSV</button><button disabled={!report} onClick={()=>exportRows('skymeet-attendance-visits.csv',[['Name','Participant key','Session','Joined','Left','Minutes','Exit reason'],...visits.map(r=>[r.name,r.personId,r.meetingId,date(r.joinedAt),date(r.leftAt),(Math.max(0,(r.leftAt||report.now)-r.joinedAt)/60000).toFixed(2),r.endReason])])}>Visit log CSV</button></div><p className="attendance-note">{rows.length} participant/session entries · {rows.filter(r=>r.live).length} currently present. Tracking starts on admission, not in the waiting room. Identity is based on this browser’s saved participant key; names are self-reported. Different devices appear separately.</p><div className="attendance-table"><table><thead><tr><th>Name</th><th>Session</th><th>First joined</th><th>Last left</th><th>Total minutes</th><th>Visits</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.personId+':'+r.meetingId}><td>{r.name}</td><td>{date(report.meetings.find(m=>m.id===r.meetingId)?.startedAt)}</td><td>{date(r.joinedAt)}</td><td>{r.live?'—':date(r.leftAt)}</td><td>{(r.total/60000).toFixed(1)}</td><td>{r.visits}</td><td>{r.live?'Present':'Left'}</td></tr>)}</tbody></table>{report&&!rows.length&&<p>No attendance records match this filter.</p>}</div><p className="attendance-note">A crash uses the last saved heartbeat as an estimated leave time. Absence/late labels require an enrolled roster and scheduled start time, which this meeting app does not yet store.</p></section>;
}
