import React,{useEffect,useRef,useState} from 'react';
import './studio.css';
const uid=()=>crypto.randomUUID();
const tools=[['select','↖ Select'],['pan','✋ Pan'],['pen','✎ Pen'],['eraser','⌫ Erase'],['sticky','▣ Sticky'],['text','T Text'],['rect','□ Rectangle'],['ellipse','○ Ellipse'],['diamond','◇ Diamond'],['arrow','↗ Connector'],['frame','▤ Frame']];
const save=(name,blob)=>{const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),15000);};
function lines(text,width,font){const max=Math.max(4,Math.floor(width/(font*.58)));return String(text||'').split('\n').flatMap(line=>{const result=[];let current='';for(const word of line.split(' ')){if(current.length+word.length>max){result.push(current);current='';}current+=(current?' ':'')+word;}result.push(current);return result;});}
export function BoardObject({o,objects}){
  const common={stroke:o.color,strokeWidth:o.width||3};const x=o.x,y=o.y,w=o.w,h=o.h;
  const words=<text x={x+12} y={y+28} fill={o.type==='sticky'?'#26322c':o.color} fontSize={o.fontSize||22} fontFamily="Arial, sans-serif">{lines(o.text,w-24,o.fontSize||22).slice(0,Math.max(1,Math.floor((h-18)/((o.fontSize||22)*1.25)))).map((line,i)=><tspan key={i} x={x+12} dy={i?(o.fontSize||22)*1.25:0}>{line}</tspan>)}</text>;
  if(o.type==='arrow'){const a=objects.find(v=>v.id===o.from),b=objects.find(v=>v.id===o.to);const ax=a?a.x+a.w/2:x,ay=a?a.y+a.h/2:(o.reverse?y+h:y),bx=b?b.x+b.w/2:x+w,by=b?b.y+b.h/2:(o.reverse?y:y+h);return <line x1={ax} y1={ay} x2={bx} y2={by} {...common} markerEnd="url(#arrowhead)"/>;}
  if(o.type==='pen')return <polyline points={o.points.map(p=>`${x+p[0]*w},${y+p[1]*h}`).join(' ')} fill="none" {...common} strokeLinecap="round" strokeLinejoin="round"/>;
  if(o.type==='image')return <image href={o.src} x={x} y={y} width={w} height={h} preserveAspectRatio="xMidYMid meet"/>;
  return <>{o.type==='ellipse'?<ellipse cx={x+w/2} cy={y+h/2} rx={w/2} ry={h/2} fill={o.fill} {...common}/>:o.type==='diamond'?<polygon points={`${x+w/2},${y} ${x+w},${y+h/2} ${x+w/2},${y+h} ${x},${y+h/2}`} fill={o.fill} {...common}/>:o.type!=='text'?<rect x={x} y={y} width={w} height={h} rx={o.type==='sticky'?2:8} fill={o.type==='frame'?'none':o.fill} strokeDasharray={o.type==='frame'?'10 7':undefined} {...common}/>:null}{words}</>;
}
export default function BoardStudio({state,send,host,notify,cursors,onClose,recording,connected=true}){
  const [tool,setTool]=useState('select'),[selection,setSelection]=useState([]),[ghost,setGhost]=useState([]),[color,setColor]=useState('#187e79'),[fill,setFill]=useState('#fff2ab'),[view,setView]=useState({x:-80,y:-60,zoom:1}),[pending,setPending]=useState(false),[status,setStatus]=useState('Saved'),[connecting,setConnecting]=useState(null),[draft,setDraft]=useState(''),[font,setFont]=useState(22),[inspectorOpen,setInspectorOpen]=useState(true);
  const svg=useRef(),gesture=useRef(null),cursorAt=useRef(0),upload=useRef(),importer=useRef();
  const objects=state?.objects||[];const editable=connected&&(host||state?.enabled!==false);
  const drawn=objects.map(o=>ghost.find(g=>g.id===o.id)||o).concat(ghost.filter(g=>!objects.some(o=>o.id===g.id)));
  const selected=objects.filter(o=>selection.includes(o.id));const selectedOne=selected.length===1?selected[0]:null;
  useEffect(()=>{if(selectedOne){setDraft(selectedOne.text||'');setFont(selectedOne.fontSize||22);}},[selectedOne?.id,selectedOne?.rev]);
  async function command(event,data){setPending(true);setStatus('Saving…');try{const result=await send(event,data);setStatus('Saved');return result;}catch(e){setStatus('Not saved — retry');notify(e.message);throw e;}finally{setPending(false);}}
  async function edit(changes){if(!editable)return notify('The host has locked the board.');try{await command('board-edit',{changes});}catch{await send('board-get').catch(()=>{});}}
  function changeSelected(fields){edit(selected.map(o=>({...o,...fields,expectedRev:o.rev})));}
  function remove(){if(selected.length)edit(selected.map(o=>({id:o.id,deleted:true,expectedRev:o.rev})));setSelection([]);}
  function duplicate(){const map=new Map(selected.map(o=>[o.id,uid()]));edit(selected.map(o=>({...o,id:map.get(o.id),x:o.x+30,y:o.y+30,from:map.get(o.from)||o.from,to:map.get(o.to)||o.to,locked:false,expectedRev:0})));}
  useEffect(()=>{const fn=e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove();}if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();command(e.shiftKey?'board-redo':'board-undo').catch(()=>{});}if((e.ctrlKey||e.metaKey)&&e.key==='d'){e.preventDefault();duplicate();}if(e.key==='Escape'){setSelection([]);setConnecting(null);setTool('select');}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);},[selected,state,editable]);
  function point(e){const p=svg.current.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.current.getScreenCTM().inverse());}
  function base(type,p){return {id:uid(),type,x:p.x,y:p.y,w:type==='frame'?600:200,h:type==='frame'?400:140,color,fill,text:type==='sticky'?'Write your idea':type==='text'?'Add text':type==='frame'?'Frame':'',fontSize:font,width:3,locked:false,expectedRev:0};}
  function down(e){if(e.button!==0)return;const p=point(e),id=e.target.closest('[data-object]')?.dataset.object,o=objects.find(o=>o.id===id),resize=e.target.closest('[data-resize]');svg.current.setPointerCapture(e.pointerId);
    if(tool==='pan'||e.altKey){gesture.current={type:'pan',cx:e.clientX,cy:e.clientY,view};return;}
    if(!editable)return;
    if(tool==='select'&&o){const ids=e.shiftKey?[...new Set([...selection,id])]:selection.includes(id)?selection:[id];setSelection(ids);const items=objects.filter(o=>ids.includes(o.id));if(items.some(o=>o.locked)&&!host)return;gesture.current={type:resize?'resize':'move',start:p,items};return;}
    if(tool==='select'){setSelection([]);return;}
    if(tool==='eraser'){if(o)edit([{id:o.id,deleted:true,expectedRev:o.rev}]);return;}
    if(tool==='arrow'&&o&&o.type!=='arrow'){if(!connecting){setConnecting(o.id);notify('Click the destination object to attach the connector.');return;}if(connecting!==o.id){const a=objects.find(v=>v.id===connecting);if(a)edit([{...base('arrow',a),from:a.id,to:o.id}]);setConnecting(null);}return;}
    const item=base(tool,p);if(tool==='pen')item.points=[[0,0],[.001,.001]];
    if(['sticky','text','frame'].includes(tool)){edit([item]);setSelection([item.id]);setTool('select');return;}
    gesture.current={type:'create',start:p,item,points:[p]};setGhost([item]);
  }
  function move(e){const p=point(e);if(Date.now()-cursorAt.current>120){cursorAt.current=Date.now();send('cursor',{x:p.x,y:p.y}).catch(()=>{});}const g=gesture.current;if(!g)return;
    if(g.type==='pan'){const scale=1200/(svg.current.getBoundingClientRect().width*g.view.zoom);setView({...g.view,x:g.view.x-(e.clientX-g.cx)*scale,y:g.view.y-(e.clientY-g.cy)*scale});return;}
    const dx=p.x-g.start.x,dy=p.y-g.start.y;
    if(g.type==='move')setGhost(g.items.map(o=>({...o,x:o.x+dx,y:o.y+dy})));
    if(g.type==='resize')setGhost(g.items.map(o=>({...o,w:Math.max(30,o.w+dx),h:Math.max(30,o.h+dy)})));
    if(g.type==='create'){if(g.item.type==='pen'){if(g.points.length<790)g.points.push(p);const minX=Math.min(...g.points.map(p=>p.x)),minY=Math.min(...g.points.map(p=>p.y)),w=Math.max(1,Math.max(...g.points.map(p=>p.x))-minX),h=Math.max(1,Math.max(...g.points.map(p=>p.y))-minY);setGhost([{...g.item,x:minX,y:minY,w,h,points:g.points.map(p=>[(p.x-minX)/w,(p.y-minY)/h])}]);}else setGhost([{...g.item,x:Math.min(g.start.x,p.x),y:Math.min(g.start.y,p.y),w:Math.max(10,Math.abs(dx)),h:Math.max(10,Math.abs(dy)),reverse:dx*dy<0}]);}
  }
  function up(){const g=gesture.current;gesture.current=null;if(!g||g.type==='pan')return;const changes=ghost.map(o=>({...o,expectedRev:g.items?.find(i=>i.id===o.id)?.rev||0}));setGhost([]);if(changes.length){edit(changes);if(g.type==='create')setSelection(changes.map(o=>o.id));}}
  function zoom(factor){setView(v=>({...v,zoom:Math.max(.1,Math.min(4,v.zoom*factor))}));}
  function fit(){if(!objects.length)return setView({x:-80,y:-60,zoom:1});const x=Math.min(...objects.map(o=>o.x))-50,y=Math.min(...objects.map(o=>o.y))-50,w=Math.max(...objects.map(o=>o.x+o.w))-x+50,h=Math.max(...objects.map(o=>o.y+o.h))-y+50;setView({x,y,zoom:Math.min(3,Math.max(.1,Math.min(1200/w,700/h)))});}
  function template(kind){const x=view.x+100,y=view.y+100;const names=kind==='lesson'?['Goals','Ideas & examples','Questions & next steps']:['To do','In progress','Done'];const changes=[];names.forEach((text,i)=>{const f=base('frame',{x:x+i*350,y});f.w=320;f.h=500;f.text=text;changes.push(f);for(let j=0;j<2;j++){const n=base('sticky',{x:x+i*350+30,y:y+80+j*170});n.w=250;n.text=j?'Next idea':'Add your notes';n.fill=['#fff2ab','#d4f3e5','#dce7ff'][i];changes.push(n);}});edit(changes);}
  async function imageFile(file){if(!file||!/^image\/(png|jpeg|webp)$/.test(file.type))return notify('Choose a PNG, JPEG or WebP image.');if(file.size>10000000)return notify('Choose an image below 10 MB.');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,1200/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=img.width*scale;c.height=img.height*scale;c.getContext('2d').drawImage(img,0,0,c.width,c.height);const src=c.toDataURL('image/jpeg',.65);if(src.length>400000)return notify('Image is still too large. Crop or reduce its size.');const o=base('image',{x:view.x+100,y:view.y+100});o.w=Math.min(500,c.width);o.h=o.w*c.height/c.width;o.src=src;await edit([o]);}catch{notify('Could not load this image.');}finally{URL.revokeObjectURL(url);}}
  function exportSVG(){const clone=svg.current.cloneNode(true);clone.querySelectorAll('[data-ui]').forEach(el=>el.remove());const all=objects.length?objects:[{x:0,y:0,w:1200,h:700}];const x=Math.min(...all.map(o=>o.x))-30,y=Math.min(...all.map(o=>o.y))-30,w=Math.max(...all.map(o=>o.x+o.w))-x+30,h=Math.max(...all.map(o=>o.y+o.h))-y+30;clone.setAttribute('viewBox',`${x} ${y} ${w} ${h}`);clone.setAttribute('width',String(Math.min(4000,w)));clone.setAttribute('height',String(Math.min(4000,w)*h/w));clone.setAttribute('xmlns','http://www.w3.org/2000/svg');return new XMLSerializer().serializeToString(clone);}
  async function png(){try{const url=URL.createObjectURL(new Blob([exportSVG()],{type:'image/svg+xml'}));const img=new Image();img.src=url;await img.decode();const c=document.createElement('canvas');const ratio=Math.min(1,4000/Math.max(img.width,img.height));c.width=img.width*ratio;c.height=img.height*ratio;c.getContext('2d').fillStyle='#fffdf7';c.getContext('2d').fillRect(0,0,c.width,c.height);c.getContext('2d').drawImage(img,0,0,c.width,c.height);c.toBlob(b=>b&&save('skymeet-board.png',b));URL.revokeObjectURL(url);}catch{notify('PNG export failed. Try SVG or JSON.');}}
  async function importFile(file){try{if(!file||file.size>6000000)throw Error('Maximum import size is 6 MB.');const parsed=JSON.parse(await file.text());if(!['skymeet-board-v2','aacharya-board-v2'].includes(parsed.format)||!Array.isArray(parsed.objects)||parsed.objects.length>100)throw Error('Import supports up to 100 objects per file.');const ids=new Map(parsed.objects.map(o=>[o.id,uid()]));await edit(parsed.objects.map(o=>({...o,id:ids.get(o.id),from:ids.get(o.from),to:ids.get(o.to),locked:false,expectedRev:0})));}catch(e){notify(e.message);}}
  return <section className="board-studio" aria-label="Collaborative whiteboard"><header className="studio-header"><div><strong>SkyMeet Canvas</strong><small>{!connected?'Disconnected — reconnecting':editable?'Collaborate in real time':'View only · host locked'} · {status} · {objects.length}/1500 items</small>{recording&&<small className="text-danger">● A participant is recording. Continue only with consent.</small>}</div><div className="row"><button aria-expanded={inspectorOpen} aria-controls="board-inspector" onClick={()=>setInspectorOpen(v=>!v)}>{inspectorOpen?'Hide tools':'Show tools'}</button><button onClick={onClose}>Back to meeting</button></div></header>
    <div className="studio-tools">{tools.map(([id,label])=><button key={id} className={tool===id?'chosen':''} disabled={(!editable&&id!=='pan')||pending} onClick={()=>{setTool(id);setConnecting(null);}}>{label}</button>)}<label>Ink<input aria-label="Stroke color" type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label>Fill<input aria-label="Shape fill" type="color" value={fill} onChange={e=>setFill(e.target.value)}/></label><button disabled={!editable||pending} onClick={()=>command('board-undo').catch(()=>{})}>↶ Undo</button><button disabled={!editable||pending} onClick={()=>command('board-redo').catch(()=>{})}>↷ Redo</button><button disabled={!editable} onClick={()=>upload.current.click()} title="Upload PNG, JPEG or WebP image">＋ Add image</button><input ref={upload} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{imageFile(e.target.files[0]);e.target.value='';}}/></div>
    <div className="studio-workspace"><div className="board-canvas"><svg ref={svg} viewBox={`${view.x} ${view.y} ${1200/view.zoom} ${700/view.zoom}`} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{gesture.current=null;setGhost([]);}} onWheel={e=>{if(e.ctrlKey||e.metaKey)zoom(e.deltaY<0?1.1:.9);else setView(v=>({...v,x:v.x+e.deltaX/v.zoom,y:v.y+e.deltaY/v.zoom}));}} aria-label="Board canvas"><defs><marker id="arrowhead" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="context-stroke"/></marker></defs>{drawn.map(o=><g key={o.id} data-object={o.id}><BoardObject o={o} objects={drawn}/>{selection.includes(o.id)&&<g data-ui="selection"><rect x={o.x-4} y={o.y-4} width={o.w+8} height={o.h+8} fill="none" stroke="#3a7df4" strokeWidth={2/view.zoom}/><rect data-resize="true" x={o.x+o.w-6/view.zoom} y={o.y+o.h-6/view.zoom} width={12/view.zoom} height={12/view.zoom} fill="#3a7df4"/></g>}</g>)}{Object.values(cursors||{}).filter(c=>Date.now()-c.at<5000).map(c=><g key={c.id} data-ui="cursor" transform={`translate(${c.x},${c.y})`}><path d="M0 0v18l5-6h10z" fill="#cc5171"/><text x="18" y="20" fontSize="14" fill="#923e57">{c.name}</text></g>)}</svg><div className="zoom-controls"><button aria-label="Zoom out" onClick={()=>zoom(.8)}>−</button><span>{Math.round(view.zoom*100)}%</span><button aria-label="Zoom in" onClick={()=>zoom(1.25)}>+</button><button onClick={fit}>Fit all</button><button onClick={()=>setView({x:-80,y:-60,zoom:1})}>Reset view</button></div></div>
    <aside id="board-inspector" className="studio-inspector" hidden={!inspectorOpen}><h3>{selected.length?`${selected.length} selected`:'Board tools'}</h3>{selected.length>0&&<><p className="muted">Shift-click to select multiple. Drag to move; use the blue corner to resize.</p>{selectedOne&&<><label>Text<textarea aria-label="Selected object text" value={draft} maxLength={3000} onChange={e=>setDraft(e.target.value)}/></label><label>Font size<input type="number" min="12" max="96" value={font} onChange={e=>setFont(Number(e.target.value))}/></label><button disabled={!editable||pending} onClick={()=>changeSelected({text:draft,fontSize:font,color,fill})}>Apply text & style</button></>}<div className="inspector-actions"><button disabled={!editable||pending} onClick={duplicate}>Duplicate</button><button disabled={!editable||pending} onClick={remove}>Delete</button>{host&&<button onClick={()=>changeSelected({locked:!selected.every(o=>o.locked)})}>{selected.every(o=>o.locked)?'Unlock':'Lock'} items</button>}{selected.length>1&&<><button onClick={()=>edit(selected.map(o=>({...o,x:Math.min(...selected.map(o=>o.x)),expectedRev:o.rev})))}>Align left</button><button onClick={()=>edit(selected.map(o=>({...o,y:Math.min(...selected.map(o=>o.y)),expectedRev:o.rev})))}>Align top</button></>}</div></>}
    <h3>Templates</h3><button disabled={!editable||pending} onClick={()=>template('lesson')}>Workshop planner</button><button disabled={!editable||pending} onClick={()=>template('kanban')}>Kanban board</button><h3>Export & backup</h3><button onClick={()=>save('skymeet-board.svg',new Blob([exportSVG()],{type:'image/svg+xml'}))}>SVG</button><button onClick={png}>PNG</button><button onClick={()=>save('skymeet-board.json',new Blob([JSON.stringify({format:'skymeet-board-v2',objects},null,2)],{type:'application/json'}))}>JSON backup</button><button disabled={!editable} onClick={()=>importer.current.click()}>Import JSON (up to 100 items)</button><input hidden ref={importer} type="file" accept=".json" onChange={e=>{importFile(e.target.files[0]);e.target.value='';}}/>{host&&<button className="text-danger" onClick={()=>confirm('Clear the whole board for everyone? This cannot be undone. Export a backup first.')&&command('board-clear').catch(()=>{})}>Clear board</button>}<p className="muted">Pan with the hand tool or Alt-drag. Scroll to move; Ctrl/⌘-scroll to zoom. Connect two objects by clicking them with Connector. Frame movement does not move contained objects: Shift-select them together.</p></aside></div></section>;
}
